Certain elements require the use of https://pagero.github.io/puf-code-lists/[PUF specific code lists^]. Below you will find the lists and where the lists are applicable.

In some of these code lists PUF only points towards an external code list to be used.

Other times the code list to be used is a mix between values defined specifically for PUF and other external list(s).

Lastly, in some cases, *all* the values are defined solely for PUF.

=== Code lists for coded elements

.Table of the code lists used
[%autowidth.stretch]
|===
|Business Term |Path |listID

|Mime code
|`cac:DocumentResponse/cac:Response/ext:UBLExtensions/ext:UBLExtension` + 
`[ext:ExtensionURI='urn:pagero:ExtensionComponent:1.0:PageroExtension` +
`:ResponseExtension']/ext:ExtensionContent/puf:PageroExtension/` +
`puf:ResponseExtension/puf:AdditionalDocumentReference/` +
`cac:Attachment/cbc:EmbeddedDocumentBinaryObject/@mimeCode`
|https://pagero.github.io/puf-code-lists/#_puf_006_mimecodes[PUF-006-MIMECODES^]

|Electronic address scheme
|`cac:AccountingSupplierParty/cac:Party/cbc:EndpointID/@schemeID` +
`cac:AccountingCustomerParty/cac:Party/cbc:EndpointID/@schemeID` +
|https://pagero.github.io/puf-code-lists/#_puf_007_endpointscheme[PUF-007-ENDPOINTSCHEME^]

|Identification scheme
|`cac:AccountingSupplierParty/cac:Party/cac:PartyIdentification/ +
cbc:ID/@schemeID` +
`cac:AccountingSupplierParty/cac:Party/cac:PartyLegalEntity/ +
cbc:CompanyID/@schemeID` +
|https://pagero.github.io/puf-code-lists/#_puf_008_identificationscheme[PUF-008-IDENTIFICATIONSCHEME^]

|Invoice status codes 
|`cac:DocumentResponse/cac:Response/cbc:ResponseCode`
|https://pagero.github.io/puf-code-lists/#_puf_016_invoicestatuscode[PUF-016-INVOICESTATUSCODE^]
|===

