.Elements available in cac:Response
|===
|Path |Description

|`ext:UBLExtensions`
|**Extension Content** +
Extension is added to provide additional information in the `cac:Response` element, added elements in regards to `ext:UBLExtensions` for `cac:Response` can be found below: +
<<_response_extension>>.

|`cbc:ResponseCode`
|**Invoice status** +
A code stating the status of the invoice in the process. +
_Value according to code list +
https://pagero.github.io/puf-code-lists/#_puf_016_invoicestatuscode[PUF-016-INVOICESTATUSCODE^]._

|`cac:Status/cbc:StatusReasonCode`
|**Status reason code** +
A code defining a clarification given for the status. +


The primary purpose of the `cac:Status` group is to explain *why* a given status is issued. However, the group can be *repeated* to also convey a *requested action* from the recipient (e.g. requesting that a new invoice is issued). In that case, an additional `cac:Status` entry should be included with a code from the https://docs.peppol.eu/poacc/upgrade-3/codelist/OPStatusAction/[OPStatusAction^] code list.

|`cac:Status/cbc:StatusReasonCode/@listID`
|**Status reason code list identifier** +
List identifier identifying which code list the `cbc:StatusReasonCode` value belongs to. +
`@listID` is **not required** by PUF, but should be included when following Peppol rules. +

For **status clarification reasons** (i.e. *why* the status is given), set `@listID` to `OPStatusReason` and use a code from the Peppol Status Clarification Reason code list: +
https://docs.peppol.eu/poacc/upgrade-3/syntax/InvoiceResponse/cac-DocumentResponse/cac-Response/cac-Status/cbc-StatusReasonCode/[Peppol Status Clarification Reason codes^]. +

For **requested actions** (i.e. what the recipient is asked to *do*), set `@listID` to `OPStatusAction` and use a code from the OPStatusAction code list: +
https://docs.peppol.eu/poacc/upgrade-3/codelist/OPStatusAction/[OPStatusAction^].

|`cac:Status/cbc:StatusReason`
|**Status reason text** +
A free-text explanation of the clarification or requested action given for the status.

|===

*Example* +
_cac:Response with example values_

[source,xml]
----
<ApplicationResponse>
    <!-- Code omitted for clarity -->
    <cac:DocumentResponse>
        <cac:Response>
            <ext:UBLExtensions>
                <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:ResponseExtension</ext:ExtensionURI>
                    <ext:ExtensionContent>
                        <puf:PageroExtension>
                            <puf:ResponseExtension>
                                <puf:ReferencedDocumentInterchangeID>
                                    <cbc:ID>123456789</cbc:ID>
                                </puf:ReferencedDocumentInterchangeID>
                                <puf:DocumentMatchingID>
                                    <!-- Either cbc:ID or cbc:UUID can be used, see Extensions documentation -->
                                    <cbc:ID>123456789</cbc:ID>
                                    <cbc:UUID>4408ca72-f3c0-11ed-a05b-0242ac120003</cbc:UUID>
                                </puf:DocumentMatchingID>
                                <puf:AdditionalDocumentReference>
                                    <cbc:ID>1456123</cbc:ID>
                                    <cbc:DocumentTypeCode>M</cbc:DocumentTypeCode>
                                    <cbc:DocumentDescription>LCD</cbc:DocumentDescription>
                                    <cac:Attachment>
                                        <cbc:EmbeddedDocumentBinaryObject filename="123456789_12345.xml" mimeCode="application/xml">U29tZSBkb2N1bWVudA==</cbc:EmbeddedDocumentBinaryObject>
                                    </cac:Attachment>
                                </puf:AdditionalDocumentReference>
                            </puf:ResponseExtension>
                        </puf:PageroExtension>
                    </ext:ExtensionContent>
                </ext:UBLExtension>
            </ext:UBLExtensions>
            <cbc:ResponseCode>APPROVED</cbc:ResponseCode>
            <cac:Status>
                <cbc:StatusReasonCode>XSD_ZATCA_VALID</cbc:StatusReasonCode>
                <cbc:StatusReason>Complied with UBL 2.1 standards in line with ZATCA specifications</cbc:StatusReason>
            </cac:Status>
        </cac:Response>
        <!-- Code omitted for clarity -->
</ApplicationResponse>
----
