==== puf:ResponseExtension

Below table shows the definition of elements added to the extension `puf:PageroExtension/puf:ResponseExtension`.

.Elements added in puf:ResponseExtension
|===
|Element |Description

|`puf:ReferencedDocumentInterchangeID/cbc:ID`
|**Referenced document interchange identifier** +
The interchange id of the referenced document (if sent by the issuer). +
This ID is applicable when you **_receive a response_**. Then this ID will be the interchange ID (if sent) of the Invoice.

|`puf:DocumentMatchingID/cbc:ID`
|**Referenced document matching identifier** +
The unique Pagero ID used to match the response to an Invoice. +
This ID is applicable when you **_send a response_**. +
Then this ID can be sent to facilitate a matching/connection between the response to the Invoice in Pagero Online.

|`puf:DocumentMatchingID/cbc:UUID`
|**Referenced API document matching identifier** +
The unique Pagero UUID used to match the response to an Invoice. +
This ID is applicable when you **_send a response_**. +
The UUID is only availble via **Document API** when using https://pagero.github.io/document-api-doc/#tag/document[GET^] documents.

|`puf:AdditionalDocumentReference/cbc:ID`
|**Additional document reference identifier** +
If there are any attachments that relates to the response. +
Identifier of the additional document reference.

|`puf:AdditionalDocumentReference/cbc:DocumentTypeCode`
|**Additional document reference type code** +
Type of attachment. + 
**M** = Miscellaneous

|`puf:AdditionalDocumentReference/cbc:DocumentDescription`
|**Additional document reference description** +
Description of the attached document.

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject/@filename`
|**Additional document reference filename** +
Filename of the attached document.

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject/@mimeCode`
|**Additional document reference MIME code** +
MIME code of the attached document. + 
Supported MIME codes can be found in the code list +
https://pagero.github.io/puf-code-lists/#_puf_006_mimecodes[PUF-006-MIMECODES^].

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject`
|**Additional document reference binary object** +
The attached document embedded as binary object (Base64).

|===

See example below as well as the URI to be used for this extension.

*Example* +
_puf:ResponseExtension with sample values._
[source,xml]
----
<ApplicationResponse>
    <!-- Code omitted for clarity -->
    <cac:DocumentResponse>
        <cac:Response>
            <ext:UBLExtensions>
                <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:ResponseExtension</ext:ExtensionURI>
                    <ext:ExtensionContent>
                        <puf:PageroExtension>
                            <puf:ResponseExtension>
                                <puf:ReferencedDocumentInterchangeID>
                                    <cbc:ID>123456789</cbc:ID>
                                </puf:ReferencedDocumentInterchangeID>
                                <puf:DocumentMatchingID>
                                    <!-- Either cbc:ID or cbc:UUID can be used, see Extensions documentation -->
                                    <cbc:ID>123456789</cbc:ID>
                                    <cbc:UUID>4408ca72-f3c0-11ed-a05b-0242ac120003</cbc:UUID>
                                </puf:DocumentMatchingID>
                                <puf:AdditionalDocumentReference>
                                    <cbc:ID>1456123</cbc:ID>
                                    <cbc:DocumentTypeCode>M</cbc:DocumentTypeCode>
                                    <cbc:DocumentDescription>LCD</cbc:DocumentDescription>
                                    <cac:Attachment>
                                        <cbc:EmbeddedDocumentBinaryObject filename="123456789_12345.xml" mimeCode="application/xml">U29tZSBkb2N1bWVudA==</cbc:EmbeddedDocumentBinaryObject>
                                    </cac:Attachment>
                                </puf:AdditionalDocumentReference>
                            </puf:ResponseExtension>
                        </puf:PageroExtension>
                    </ext:ExtensionContent>
                </ext:UBLExtension>
            </ext:UBLExtensions>
        </cac:Response>
        <!-- Code omitted for clarity -->
</ApplicationResponse>
----
