==== puf:ResponseExtension

Below tables shows the definition of elements added to the extension `puf:PageroExtension/puf:ResponseExtension`. 

.Elements added in puf:ResponseExtension relating to RestrictedInformation.
[.response-extension-table]
[%stretch,cols="1,1"]
|===
|Element |Description

|`puf:RestrictedInformation/puf:Key +
puf:RestrictedInformation/puf:Value`
|**Returnable restricted information** +
From PUF Billing documents sent to Pagero, restricted information values on document level with keys prefixed by "returnInResponse_" will be returned in the response message with the same key and value.

|===

.Elements added in puf:ResponseExtension relating to document/reference matching.
[.response-extension-table]
[%stretch,cols="1,1"]
|===
|Element |Description

|`puf:ReferencedDocumentInterchangeID/cbc:ID`
|**Referenced document interchange identifier** +
The interchange id of the referenced document (if sent by the issuer). +
This ID is applicable when you **_receive a response_**. Then this ID will be the interchange ID (if sent) of the Invoice.

|`puf:DocumentMatchingID/cbc:ID`
|**Referenced document matching identifier** +
The unique Pagero ID used to match the response to an Invoice. +
This ID is applicable when you **_send a response_**. +
Then this ID can be sent to facilitate a matching/connection between the response to the Invoice in Pagero Online.

|`puf:DocumentMatchingID/cbc:UUID`
|**Referenced API document matching identifier** +
The unique Pagero UUID used to match the response to an Invoice. +
This ID is applicable when you **_send a response_**. +
The UUID is only availble via **Document API** when using https://pagero.github.io/document-api-doc/#tag/document[GET^] documents.

|===

.Elements added in puf:ResponseExtension relating to attachments and related documents. 
[.response-extension-table]
[%stretch,cols="1,1"]
|===
|Element |Description

|`puf:AdditionalDocumentReference/cbc:ID`
|**Additional document reference identifier** +
If there are any attachments that relates to the response. +
Identifier of the additional document reference.

|`puf:AdditionalDocumentReference/cbc:DocumentTypeCode`
|**Additional document reference type code** +
Type of attachment. + 
**M** = Miscellaneous

|`puf:AdditionalDocumentReference/cbc:DocumentDescription`
|**Additional document reference description** +
Description of the attached document.

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject/@filename`
|**Additional document reference filename** +
Filename of the attached document.

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject/@mimeCode`
|**Additional document reference MIME code** +
MIME code of the attached document. + 
Supported MIME codes can be found in the code list +
https://pagero.github.io/puf-code-lists/#_puf_006_mimecodes[PUF-006-MIMECODES^].

|`puf:AdditionalDocumentReference/cac:Attachment/ + 
cbc:EmbeddedDocumentBinaryObject`
|**Additional document reference binary object** +
The attached document embedded as binary object (Base64).

|===
.Elements added in puf:ResponseExtension relating to amounts. 
[.response-extension-table]
[%stretch,cols="1,1"]
|===
|Element |Description

|`puf:Amounts/puf:Amount/puf:AmountType`
|**Amount type** +
The type of amount that is being specified. +
AmountType code currently depend on country guidelines. See section <<_country_specifics>> for more details on how it's handled in each country.

|`puf:Amounts/puf:Amount/cbc:TaxExclusiveAmount`
|**Net amount** +
The net amount (excl. taxes) for the specified amount type.

|`puf:Amounts/puf:Amount/cbc:TaxInclusiveAmount`
|**Total amount** +
The total amount (incl. taxes) for the specified amount type.

|`puf:Amounts/puf:Amount/cac:ClassifiedTaxCategory/cbc:Percent`
|**Tax rate** +
The tax rate applicable for the specified amount type.

|===

See example below as well as the URI to be used for this extension.

*Example* +
_puf:ResponseExtension with sample values._
[%nowrap]
[source,xml]
----
<ApplicationResponse>
    <!-- Code omitted for clarity -->
    <cac:DocumentResponse>
        <cac:Response>
            <ext:UBLExtensions>
                <ext:UBLExtension>
                    <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:ResponseExtension</ext:ExtensionURI>
                    <ext:ExtensionContent>
                        <puf:PageroExtension>
                            <puf:ResponseExtension>
                                <puf:ReferencedDocumentInterchangeID>
                                    <cbc:ID>123456789</cbc:ID>
                                </puf:ReferencedDocumentInterchangeID>
                                <puf:DocumentMatchingID>
                                    <!-- Either cbc:ID or cbc:UUID can be used, see Extensions documentation -->
                                    <cbc:ID>123456789</cbc:ID>
                                    <cbc:UUID>4408ca72-f3c0-11ed-a05b-0242ac120003</cbc:UUID>
                                </puf:DocumentMatchingID>
                                <puf:AdditionalDocumentReference>
                                    <cbc:ID>1456123</cbc:ID>
                                    <cbc:DocumentTypeCode>M</cbc:DocumentTypeCode>
                                    <cbc:DocumentDescription>LCD</cbc:DocumentDescription>
                                    <cac:Attachment>
                                        <cbc:EmbeddedDocumentBinaryObject filename="123456789_12345.xml" mimeCode="application/xml">U29tZSBkb2N1bWVudA==</cbc:EmbeddedDocumentBinaryObject>
                                    </cac:Attachment>
                                </puf:AdditionalDocumentReference>
                                <puf:Amounts>
                                    <puf:Amount>
                                        <puf:AmountType>MEN</puf:AmountType>
                                        <cbc:TaxExclusiveAmount currencyID="EUR">100.00</cbc:TaxExclusiveAmount>
                                        <cbc:TaxInclusiveAmount currencyID="EUR">120.00</cbc:TaxInclusiveAmount>
                                        <puf:ClassifiedTaxCategory>
                                            <cbc:Percent>20</cbc:Percent>
                                        </puf:ClassifiedTaxCategory>
                                    </puf:Amount>
                                    <puf:Amount>
                                        <puf:AmountType>MEN</puf:AmountType>
                                        <cbc:TaxExclusiveAmount currencyID="EUR">10.00</cbc:TaxExclusiveAmount>
                                        <cbc:TaxInclusiveAmount currencyID="EUR">11.00</cbc:TaxInclusiveAmount>
                                        <puf:ClassifiedTaxCategory>
                                            <cbc:Percent>10</cbc:Percent>
                                        </puf:ClassifiedTaxCategory>
                                    </puf:Amount>
                                </puf:Amounts>
                            </puf:ResponseExtension>
                        </puf:PageroExtension>
                    </ext:ExtensionContent>
                </ext:UBLExtension>
            </ext:UBLExtensions>
        </cac:Response>
        <!-- Code omitted for clarity -->
</ApplicationResponse>
----

