==== puf:StatusExtension

Below tables shows the definition of elements added to the extension `puf:PageroExtension/puf:StatusExtension`. 

.Elements added in puf:StatusExtension relating to amounts. 
[.status-extension-table]
[%stretch,cols="1,1"]
|===
|Element |Description

|`puf:Amounts/puf:Amount/puf:AmountType`
|**Amount type** +
The type of amount that is being specified. +
AmountType code currently depend on country guidelines. See section <<_country_specifics>> for more details on how it's handled in each country.

|`puf:Amounts/puf:Amount/cbc:TaxExclusiveAmount`
|**Net amount** +
The net amount (excl. taxes) for the specified amount type.

|`puf:Amounts/puf:Amount/cbc:TaxInclusiveAmount`
|**Total amount** +
The total amount (incl. taxes) for the specified amount type.

|`puf:Amounts/puf:Amount/cac:ClassifiedTaxCategory/cbc:Percent`
|**Tax rate** +
The tax rate applicable for the specified amount type.
|===

See example below as well as the URI to be used for this extension.

*Example* +
_puf:StatusExtension with sample values. The example scenario illustrated below is an invoice for €1310 (incl. VAT) with two VAT rates (20 % and 10 %). The taxpayer reports that two amounts have been paid: €120 (incl. 20 % VAT) and €11 (incl. 10 % VAT). In addition to this, the taxpayer also informs the recipient that they have €1080 (incl. 20 % VAT) and €99 (incl. 10 % VAT) remaining to be paid (RAP)._
[%nowrap]
[source,xml]
----
<ApplicationResponse>
    <!-- Code omitted for clarity -->
    <cac:DocumentResponse>
        <cac:Response>
        <!-- Code omitted for clarity -->
            <cac:Status>
                <ext:UBLExtensions>
                    <ext:UBLExtension>
                        <ext:ExtensionURI>urn:pagero:ExtensionComponent:1.0:PageroExtension:StatusExtension</ext:ExtensionURI>
                        <ext:ExtensionContent>
                            <puf:PageroExtension>
                                <puf:StatusExtension>
                                    <!-- Code omitted for clarity -->
                                    <puf:Amounts>
                                        <puf:Amount>
                                            <puf:AmountType>MEN</puf:AmountType>
                                            <cbc:TaxInclusiveAmount currencyID="EUR">120.00</cbc:TaxInclusiveAmount>
                                            <puf:ClassifiedTaxCategory>
                                                <cbc:Percent>20</cbc:Percent>
                                                <cac:TaxScheme>
                                                    <cbc:ID>VAT</cbc:ID>
                                                </cac:TaxScheme>
                                            </puf:ClassifiedTaxCategory>
                                        </puf:Amount>
                                        <puf:Amount>
                                            <puf:AmountType>MEN</puf:AmountType>
                                            <cbc:TaxInclusiveAmount currencyID="EUR">11.00</cbc:TaxInclusiveAmount>
                                            <puf:ClassifiedTaxCategory>
                                                <cbc:Percent>10</cbc:Percent>
                                                <cac:TaxScheme>
                                                    <cbc:ID>VAT</cbc:ID>
                                                </cac:TaxScheme>
                                            </puf:ClassifiedTaxCategory>
                                        </puf:Amount>
                                        <puf:Amount>
                                            <puf:AmountType>RAP</puf:AmountType>
                                            <cbc:TaxInclusiveAmount currencyID="EUR">1080.00</cbc:TaxInclusiveAmount>
                                            <puf:ClassifiedTaxCategory>
                                                <cbc:Percent>20</cbc:Percent>
                                                <cac:TaxScheme>
                                                    <cbc:ID>VAT</cbc:ID>
                                                </cac:TaxScheme>
                                            </puf:ClassifiedTaxCategory>
                                        </puf:Amount>
                                        <puf:Amount>
                                            <puf:AmountType>RAP</puf:AmountType>
                                            <cbc:TaxInclusiveAmount currencyID="EUR">99.00</cbc:TaxInclusiveAmount>
                                            <puf:ClassifiedTaxCategory>
                                                <cbc:Percent>10</cbc:Percent>
                                                <cac:TaxScheme>
                                                    <cbc:ID>VAT</cbc:ID>
                                                </cac:TaxScheme>
                                            </puf:ClassifiedTaxCategory>
                                        </puf:Amount>
                                    </puf:Amounts>
                                </puf:StatusExtension>
                            </puf:PageroExtension>
                        </ext:ExtensionContent>
                    </ext:UBLExtension>
                </ext:UBLExtensions>
            </cac:Status>
        </cac:Response>
        <!-- Code omitted for clarity -->
</ApplicationResponse>
----